name = "whiteboard-api"
main = "worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

routes = [
  { pattern = "whiteboard-api.morganambrose.work/*", zone_name = "morganambrose.work" }
]

[vars]
GITHUB_REPO = "Law-Fifteen/Whiteboard"
NOTIFY_EMAILS = "MorganAmbrose@Proton.me,Phoenxityy@gmail.com"
